# Generated by Django 4.1 on 2024-12-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_reservations_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservations",
            options={
                "verbose_name": "Бронировние",
                "verbose_name_plural": "Бронировние",
            },
        ),
    ]
